Repository precice/precice.github.io, pull requests merged in 2023-04, with the labels that each got.

#223 Update porting guide v3
  pages/docs/couple-your-code/couple-your-code-porting-v2-3.md
Labels: breaking change, documentation

#256 Porting guide: make dt mandatory
  pages/docs/couple-your-code/couple-your-code-porting-v2-3.md
Labels: breaking change, documentation

#254 Update action config docs to v3
  pages/docs/configuration/configuration-action.md
Labels: breaking change

#263 Add a page for previous versions
  _data/sidebars/docs_sidebar.yml
  pages/docs/fundamentals/fundamentals-previous-versions.md
Labels: content

#264 Add community section in landing page
  images/events/precice2023-group.jpg
  pages/index.html
Labels: content, technical
