Repository precice/precice.github.io, pull requests merged in 2024-04, with the labels that each got.

#326 Add comments on pitfalls with very small time step sizes
  pages/docs/couple-your-code/couple-your-code-time-step-sizes.md
Labels: content

#368 Introduce folders in the tutorials sidebar and sort tutorials
  _data/sidebars/tutorial_sidebar.yml
  pages/tutorials/tutorials-visualization.md
  pages/tutorials/tutorials.md
Labels: technical

#377 Add link-only property to folderitems
  _data/sidebars/tutorial_sidebar.yml
  _includes/sidebar.html
Labels: bug
